-- 009_backup_and_import_civil_list.sql
-- Backs up existing employee_profiles and populates official MoSPI ISS Civil List dataset.
-- Total CSV records: 213
-- Idempotent and duplicate-safe using employee_id (oid_no).

-- 1. Create backup of existing employee_profiles if backup table does not exist
CREATE TABLE IF NOT EXISTS public.employee_profiles_backup AS 
SELECT * FROM public.employee_profiles;

-- 2. Clean up dummy/demo employee records that were created for testing
-- (Backup is safely stored in employee_profiles_backup above)
DELETE FROM public.employee_profiles 
WHERE employee_id IN ('MOSPI-EMP-001', 'EMP-1002', 'EMP-ALPHA-01', 'EMP-BETA-02', 'MOSPI - 200', 'MOSPI -4102', 'MOSPI-1242', 'MOSPI-1232', '12ka4-42ka1', 'MOSPI - 99', 'MOSPI-1234');

-- 3. Upsert official MoSPI Civil List employee records
INSERT INTO public.employee_profiles (
  employee_id,
  name,
  designation_id,
  department,
  experience_years
)
VALUES
  ('921007', 'Siddhartha Kundu', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, HSD Kolkata', 32),
  ('921008', 'Praveen Shukla', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, ASPD, NSO New Delhi', 32),
  ('921009', 'Bandana Sen', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 32),
  ('921010', 'Ajay Baksi', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'M/o Jal Shakti, D/o Water Resources, RD & GR New Delhi', 32),
  ('921013', 'Dr Chandramani', (SELECT id FROM public.designations WHERE name = 'Chief Vigilance Officer' LIMIT 1), 'Ministry of Railways, RCIL New Delhi', 32),
  ('921015', 'Kishore Kumar', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, CQCD New Delhi', 32),
  ('921016', 'M K Ujjainia', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'M/o Rural Dev., D/o Rural Dev. New Delhi', 32),
  ('921017', 'Rajkumar', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, PSD, NSO New Delhi', 32),
  ('921018', 'Kishor Baburao Surwade', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, CDD New Delhi', 32),
  ('951003', 'Salil K. Mukhopadhyay', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, EnSD Kolkata', 28),
  ('951004', 'Rajesh Bhatia', (SELECT id FROM public.designations WHERE name = 'Additional Director General' LIMIT 1), 'MoSPI, CICD New Delhi', 28),
  ('991002', 'Rajnesh Mathur', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, EnSU Ahmedabad', 25),
  ('991003', 'Anindita Sinharay', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, CDD New Delhi', 25),
  ('991004', 'Sourav Chakrabortty', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, HSD Kolkata', 25),
  ('991005', 'S Bhattacharya', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Agriculture & FW, SDDS New Delhi', 25),
  ('991007', 'Dr. Rahul S Jagtap', (SELECT id FROM public.designations WHERE name = 'Chief Vigilance Officer' LIMIT 1), 'M/o Chemical & Fertilizer, Rashtriya Chemicals and Fertilizers Limited Mumbai', 25),
  ('991008', 'Anindya Banerjee', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Agriculture & FW, DES New Delhi', 25),
  ('991009', 'M S Subramanya Rao', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, CQCD New Delhi', 25),
  ('991010', 'Dr Rajeswari Kasturi', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Health & FW, NTI Bangalore', 25),
  ('991011', 'Avanish Kumar Mishra', (SELECT id FROM public.designations WHERE name = 'Controller of Aid Accounts & Audit' LIMIT 1), 'M/o Finance., D/o Economic Affairs New Delhi', 25),
  ('991012', 'Sanjib Basu', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, RO, NSO(FOD) Kolkata', 25),
  ('991013', 'S Leena', (SELECT id FROM public.designations WHERE name = 'Advisor & Faculty' LIMIT 1), 'Govt. of Karnataka Bangalore', 25),
  ('991014', 'Deepti Srivastava', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, PSD, NSO New Delhi', 25),
  ('031014', 'Naveen Kumar Vidyarthi', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Agriculture & FW, CFCC New Delhi', 21),
  ('031015', 'Hema Jaiswal', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Finance., D/o Expenditure New Delhi', 21),
  ('031016', 'Mini Prasannakumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o New & Renewable Energy New Delhi', 21),
  ('031017', 'Uppala Srinivas', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, ZO, NSO(FOD) Nagpur', 21),
  ('042024', 'Jagat Hazarika', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Fisheries, Animal Husbandry & Dairying, D/o Animal Husbandry & Dairying New Delhi', 20),
  ('071001', 'Kanishk Kant Srivastava', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'M/o Chemical & Fertilizer, D/o Chemical & Petrochemical New Delhi', 19),
  ('071013', 'Akhilesh Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Textile New Delhi', 19),
  ('071011', 'Dr Sanjay Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Rural Dev., D/o Land Resources New Delhi', 19),
  ('071007', 'Raushan Kumar Choudhary', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, FOD(Hqrs.), NSO New Delhi', 19),
  ('071010', 'Rajeev Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, NAD, NSO New Delhi', 19),
  ('062018', 'Vinit Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, RO, NSO(FOD) Ranchi', 18),
  ('062019', 'Mool Chand Bhaskar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'M/o Defence New Delhi', 18),
  ('081001', 'Neha Srivastava', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 18),
  ('081002', 'Dr Jitendra Singh Tomar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 18),
  ('081003', 'Uttam Kumar Majee', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, HSD Kolkata', 18),
  ('081004', 'Soumya P Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, State Unit, CICD New Delhi', 18),
  ('081005', 'Shruti Shukla', (SELECT id FROM public.designations WHERE name = 'Deputy Director General' LIMIT 1), 'MoSPI, HSD Kolkata', 18),
  ('081006', 'Dr Akshya Kumar Panigrahi', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, EnSD, NSO Kolkata', 18),
  ('081007', 'Saurabh Kumar Dubey', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, EnSD, NSO Kolkata', 18),
  ('081009', 'Cyriac George', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, Coordination Unit, CICD New Delhi', 18),
  ('081010', 'Kumar Sundaram', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'M/o Health & FW, D/o H & FW New Delhi', 18),
  ('081011', 'Fakhre Alam', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 18),
  ('081012', 'Shivnath Singh Jadawat', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, Training Unit, CDD New Delhi', 18),
  ('081013', 'Muhammed Yasir F', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'MoSPI, NSO (FOD) RO Kozhikode', 18),
  ('081014', 'Sanjay Kumar', (SELECT id FROM public.designations WHERE name = 'Director' LIMIT 1), 'M/o Tourism New Delhi', 18),
  ('141034', 'Arvind Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Secretary' LIMIT 1), 'NITI Aayog New Delhi', 11),
  ('141035', 'Amitha M', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'MoSPI, NAD, NSO New Delhi', 11),
  ('141036', 'Rajesh Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Passport Officer' LIMIT 1), 'M/o External Affairs, Central Passport Organisation Jammu', 11),
  ('141037', 'Dharmender', (SELECT id FROM public.designations WHERE name = 'Deputy Secretary' LIMIT 1), 'M/o Health & FW, National Medical Commission New Delhi', 11),
  ('141038', 'Ankur Kumar', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 11),
  ('141039', 'Rohit Naagar', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 11),
  ('141040', 'Rachna Singh', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'M/o Home Affairs, O/o RGI New Delhi', 11),
  ('141041', 'Saumya Sakshi', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'MoSPI, TPP, P.I. Wing New Delhi', 11),
  ('141042', 'Joginder', (SELECT id FROM public.designations WHERE name = 'Joint Director' LIMIT 1), 'M/o MSME New Delhi', 11),
  ('981019', 'E Nagachandran', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'Ministry of Corporate Affairs New Delhi', 27),
  ('151001', 'Dona Francis', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Education, D/o Higher Edu. New Delhi', 10),
  ('151002', 'Priyanka Sethi', (SELECT id FROM public.designations WHERE name = 'Under Secretary' LIMIT 1), 'M/o External Affairs New Delhi', 10),
  ('151003', 'Apeksha Agrawal Jain', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Commerce & Ind., O/o Economic Adviser', 10),
  ('151004', 'Anshika Bhatnagar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Jal Shakti, D/o Water Resources, RD & GR New Delhi', 10),
  ('151005', 'Richy Rachel Mathew', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Agriculture & FW, Coconut Development Board Kochi', 10),
  ('151006', 'Jasleen Rekhi', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, P.I. Division, NSO New Delhi', 10),
  ('151007', 'Shipra Srivastava', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o AYUSH New Delhi', 10),
  ('151008', 'Priyanka Kumari', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Agriculture & FW, D/o Ag. & FW New Delhi', 10),
  ('151010', 'Shruti Pandey', (SELECT id FROM public.designations WHERE name = 'Deputy Passport Officer' LIMIT 1), 'Regional Passport Office Pune', 10),
  ('151011', 'Sutapa Ghosh', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, EnSD, NSO Kolkata', 10),
  ('151012', 'Tuhina Das', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Commerce & Ind., D/o Commerce New Delhi', 10),
  ('151013', 'Ishita Das', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, HSD Kolkata', 10),
  ('151014', 'Aastha Gaur', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, SSD, NSO New Delhi', 10),
  ('151015', 'Piyush Kumar Pathak', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Labour & Emp., M/o Labour New Delhi', 10),
  ('151016', 'Timan Singh', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, SSS Division, NSO New Delhi', 10),
  ('151017', 'Ranabir De', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, EnSD, NSO IS Wing Kolkata', 10),
  ('151018', 'Pankhudi Pandey', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 10),
  ('151019', 'Mukund Bihari', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Tribal Affairs New Delhi', 10),
  ('151020', 'Priyanka Nigam', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Defence, ASO/MISO/GS New Delhi', 10),
  ('151021', 'Ashish Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Ranchi', 10),
  ('151045', 'Biplab Sarkar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 10),
  ('151046', 'Shrutimala Rajbongshi', (SELECT id FROM public.designations WHERE name = 'Under Secretary' LIMIT 1), 'NEC Secretariat, Shillong', 9),
  ('151047', 'Kousik Dhara', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, HSD Kolkata', 10),
  ('151049', 'Chinneivah Haokip', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, EnSD New Delhi', 10),
  ('151050', 'Sanjeev Sharan Pandey', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Steel New Delhi', 10),
  ('152070', 'R S Verma', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, ZO, NSO(FOD) Jaipur', 9),
  ('161001', 'Aisha Saeed', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, Coordination Unit, CICD New Delhi', 9),
  ('161002', 'Priyanka S Pant', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, NAD, NSO New Delhi', 9),
  ('161003', 'Aayushi Mishra', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Chandigarh', 9),
  ('161004', 'Anu Verma', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Food Proc. Industries New Delhi', 9),
  ('161005', 'Subhankar Pramanik', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, HSD Kolkata', 9),
  ('161006', 'Ravi Meena', (SELECT id FROM public.designations WHERE name = 'Deputy Passport Officer' LIMIT 1), 'M/o External Affairs, Regional Passport Office Jaipur', 9),
  ('161007', 'Pankaj Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Health & FW, DGHS New Delhi', 9),
  ('161008', 'Sneh Kirti', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Labour & Emp., Labour Bureau Chandigarh', 9),
  ('161009', 'Priyanka Pandey', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 9),
  ('162081', 'Biju Cyriac', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Tribal Affairs New Delhi', 3),
  ('162082', 'G Lalitha', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Finance., DDM, CBIC, D/o Revenue New Delhi', 3),
  ('191002', 'Jagrati Goyal', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 6),
  ('191003', 'Priyanka Anjoy', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, NAD, NSO New Delhi', 6),
  ('191004', 'Himanshi Trivedi', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, DIID New Delhi', 6),
  ('191005', 'Bhawana Joshi', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, Coordination Unit, CICD New Delhi', 6),
  ('191006', 'Ankit Kumar Jain', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Coal New Delhi', 6),
  ('191007', 'Akshita Arora', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, FOD(Hqrs.), NSO New Delhi', 6),
  ('191008', 'Anjali Maurya', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, SSD, NSO New Delhi', 6),
  ('191009', 'Preeti Tiwari', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Home Affairs, O/o RGI New Delhi', 6),
  ('191019', 'Sharddha Pal', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Agriculture & FW, CACP New Delhi', 6),
  ('191021', 'Ashish Yadav', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Health & FW, NTI Bangalore', 6),
  ('191022', 'Abhijeet Sharma', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Civil Aviation, O/o DGCA New Delhi', 6),
  ('191023', 'Jitendra kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Labour & Emp. New Delhi', 6),
  ('191024', 'Sourav Sablania', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, PSD, NSO New Delhi', 6),
  ('191025', 'Sandipan Sarkar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, EnSD Kolkata', 6),
  ('191026', 'Dilip kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Tourism New Delhi', 6),
  ('191027', 'Ravi Shankar Verma', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Ahmedabad', 6),
  ('191028', 'Yashwant Kumar', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, MPLADS, NSO New Delhi', 6),
  ('191029', 'Himanchali Rana', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, ASPD, NSO New Delhi', 6),
  ('191030', 'Rahul Kumar Gupta', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'MoSPI, RAU New Delhi', 6),
  ('191031', 'Santhosh Naik Boda', (SELECT id FROM public.designations WHERE name = 'Deputy Director' LIMIT 1), 'M/o Labour & Emp., DGE New Delhi', 6),
  ('201008', 'Anchal Jain', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Env., Forest & Climate Change New Delhi', 4),
  ('201010', 'Sutapa Ghosh', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Kolkata', 4),
  ('201011', 'Harshvardhan Singh Garhwal', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Jaipur', 4),
  ('201012', 'Kalpna', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, FOD(Hqrs.), NSO New Delhi', 4),
  ('201013', 'Bhavna Mishra', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, HSD Kolkata', 4),
  ('201014', 'Divyanshu Mishra', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, FOD(Hqrs.), NSO New Delhi', 4),
  ('201015', 'Shikha Rai', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, ZO, NSO(FOD) Lucknow', 4),
  ('201016', 'Navdeep Kaur', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Chandigarh', 4),
  ('201017', 'Neetesh Kumar Mishra', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Aligarh (UP)', 4),
  ('201018', 'Vasumana Punj', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, ESD, NSO New Delhi', 4),
  ('201019', 'Kumar Skand', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Purnia (Bihar)', 4),
  ('201020', 'Archana Shukla', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Social Justice & Emp., D/o Social Justice New Delhi', 4),
  ('201021', 'Mamta Chaudhary', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Jodhpur (Rajasthan)', 4),
  ('201022', 'Agrawal Sachita Rakesh', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Jabalpur', 4),
  ('201023', 'Nigar Fatma', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, NAD, NSO New Delhi', 4),
  ('201024', 'Raghvendra Pandey', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, DIID New Delhi', 4),
  ('201025', 'Aditya Mandal', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 13),
  ('201026', 'Ayesha Zuhee Nizam', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Finance., TRU, D/o Revenue New Delhi', 4),
  ('201027', 'Abhishek Gaurav', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Patna', 4),
  ('201028', 'Vikas Gurjar', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, EnSU New Delhi', 4),
  ('201030', 'Vishvnath Kumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Commerce & Ind., DGFT New Delhi', 4),
  ('201031', 'Ranjana Saini', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'M/o Rural Dev., D/o Rural Dev. New Delhi', 4),
  ('221001', 'Astitva Ranjan Srivastava', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Gonda', 3),
  ('221002', 'Bappa Saha', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, RO, NSO(FOD) Port Blair', 3),
  ('221003', 'Sagnik Dey', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Midnapore', 3),
  ('221004', 'Meghal Sharma', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Udaipur', 3),
  ('221005', 'Manisha Yadav', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Hisar', 3),
  ('221007', 'Priyanshu Kumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Ambala', 3),
  ('221023', 'KM Avantika Nishad', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Sitapur', 3),
  ('221024', 'Jyoti Singharia', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Kota', 3),
  ('221025', 'Gurpreet Singh', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Hoshiarpur', 3),
  ('221026', 'Kiran', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Ujjain', 3),
  ('221027', 'Jai Prakash Sah', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Dumka', 3),
  ('221028', 'Rishabh Singh Shyam', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Bilaspur', 3),
  ('221029', 'Syed Adil Zahoor', (SELECT id FROM public.designations WHERE name = 'Assistant Director' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Baramullah', 3),
  ('232037', 'R K Mahida', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, EnSU Ahmedabad', 3),
  ('232038', 'Ravinder Kumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Ludhiana', 3),
  ('232039', 'T K Solanki', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o MSME, O/o DC, MSME Ahmedabad', 3),
  ('232040', 'A S Chauhan', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Rajkot (Gujarat)', 3),
  ('232041', 'H S Mandal', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Labour & Emp., Labour Bureau Kolkata', 3),
  ('232042', 'Deo Kumar Choudhary', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, Coordination Unit, CICD New Delhi', 3),
  ('232043', 'Radhey Shyam Sharma', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Social Justice & Emp., D/o Empowerment of Divyangjan New Delhi', 3),
  ('232044', 'R P Likhar', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Mines, IBM Nagpur', 3),
  ('232045', 'L K Ngathingkhui', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Kohima', 3),
  ('232064', 'Anis-Ul Malik', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, HSU Nagpur', 3),
  ('232065', 'Puneet Shrivastava', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, CQCD, NSO New Delhi', 3),
  ('232066', 'A Hait', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, EnSD Kolkata', 3),
  ('232067', 'S Mukherjee', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 3),
  ('232068', 'Dilli Ram Sharma', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Gangtok', 3),
  ('232069', 'S Dutta', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 3),
  ('232070', 'A Ray', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, HSD Kolkata', 3),
  ('232071', 'Manas Kumar Banerjee', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, HSD Kolkata', 3),
  ('232072', 'Jaya Pradhan', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Siliguri (WB)', 3),
  ('232074', 'Archana Verma', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Health & FW, D/o H & FW New Delhi', 3),
  ('232075', 'Anup Prasad', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Finance., Department of Public Enterprises New Delhi', 3),
  ('232076', 'Ramesh Singh', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Commerce & Ind., DGCI&S Kolkata', 3),
  ('232077', 'M M Nandakumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Agriculture & FW, DES Bangalore', 3),
  ('232078', 'G S Hiremath', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Solapur (Maharashtra)', 3),
  ('232080', 'Rajagopal Krishnan', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Mumbai', 3),
  ('232081', 'T I Trivedi', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, EnSU Ahmedabad', 3),
  ('232082', 'A P Bhadange', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, HSU Nagpur', 3),
  ('232083', 'Chandrakanta Chandela', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Jaipur', 3),
  ('232084', 'P Jaya Ramulu Peddi Reddy', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, HSU Bangalore', 3),
  ('232086', 'Anil', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Labour & Emp., Labour Bureau Chandigarh', 3),
  ('232087', 'Sailesh Kumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Petroleum & Natural Gas New Delhi', 3),
  ('232088', 'Sukhesh Chandra Das', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o MSME, O/o DC, MSME Guwahati', 3),
  ('232091', 'Pramod Kumar Mallick', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Bhubaneshwar', 3),
  ('232092', 'Judhistir Soboro', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Sambalpur', 3),
  ('232093', 'Gama Purty', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Chinsura (WB)', 3),
  ('232096', 'Arun Kumar-1', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Jalandhar City', 2),
  ('232097', 'Kunal Das Baksi', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, ZO, NSO(FOD) Kolkata', 2),
  ('232098', 'P. K. Janardhanan', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Kozhikode', 2),
  ('232102', 'Brahmanand Prasad', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Health & FW, CBHI Patna', 2),
  ('232103', 'Sankar Chakraborty', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Guwahati', 2),
  ('232105', 'Balaji S', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Pondicherry', 2),
  ('232106', 'Ajit Kumar', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Tirunelveli', 2),
  ('232107', 'Mukesh Dutt Sharma', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Fisheries, Animal Husbandry & Dairying New Delhi', 2),
  ('232108', 'V. K. Singh', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, FOD(Hqrs.), NSO New Delhi', 2),
  ('232109', 'J. P. Kushwaha', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Communication & IT, D/o of Post New Delhi', 2),
  ('242005', 'Yogendra Prasad', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Health & FW, NVBDCP New Delhi', 2),
  ('231007', 'Shivanshi Shukla', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242006', 'Sanjay Raturi', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Dehradun', 2),
  ('231008', 'Prateek Naik', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242007', 'Nikhilesh Mathuresh Biswas', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Education, D/o Higher Edu. New Delhi', 2),
  ('231009', 'Swati Gupta', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242008', 'Firoz Khan', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Kanpur', 2),
  ('231011', 'Rohit Kumar Sudhansu', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242009', 'N.K. Singh', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Imphal (Manipur)', 2),
  ('231012', 'Sumanpreet Kaur', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242027', 'S.K. Singh', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Health & FW, D/o H & FW New Delhi', 2),
  ('231033', 'Payal Meena', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, NSSTA, NSO Gr. Noida (UP)', 2),
  ('242028', 'Manas kr. Gupta', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Culture, ASI Kolkata', 1),
  ('242029', 'Y.P. Sarma Yammanur', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Vijayawada', 1),
  ('242030', 'Bobby Thomas Mathews', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Chennai', 1),
  ('242031', 'Pavitra Sewa', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Health & FW, D/o H & FW New Delhi', 1),
  ('242032', 'Anupam Deb Barman', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, SRO, NSO(FOD) Indore', 1),
  ('242033', 'Shyamal Kumar Paik', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'M/o Women & Child Development New Delhi', 1),
  ('242034', 'Arif Iqbal Bhat', (SELECT id FROM public.designations WHERE name = 'Assistant Director (Probationer)' LIMIT 1), 'MoSPI, RO, NSO(FOD) Srinagar', 1)
ON CONFLICT (employee_id) DO UPDATE SET
  name = EXCLUDED.name,
  designation_id = EXCLUDED.designation_id,
  department = EXCLUDED.department,
  experience_years = EXCLUDED.experience_years,
  updated_at = now();
